### ISSUE TITLE
FlyOS存在的问题

### ISSUE THREAD

**Issue by xingyujie** [xingyujie/flyos#14]
1.安装程序whiptailordialog
2.pywebio激活向导的密码向导+用户名欢迎
3.Android Studio打包apk，制作apt软件源（可以用docker的termux packages镜像容器批量自动打包非官方包名（自定义包名）（com.termux）的deb）
4.电脑版客户端，使用qt开发，内置ssh终端，adb调试手机flyos等
5.把海鲜为flyos写的FlyOS virtualmachinepro程序放到dev的功能17里面
（$FLYOS/virtualmachine/vm.py）
6.创建unflyos-repo(放类似mo2的定制文件，这个自己建)
7.美化pywebio，去pypi文件夹美化html，引入更多js和css，更改底部powered by版权
8.放吐槽，Github，关于到panel
9.官网升级（在做了）
10.写wiki（没想好选哪家wiki文档部署）
11.官网列一些著名支持的桌面软件列表，提醒用户安装
12.翻译flyos成英文等，官网也翻译
13.console和panel显示当前ip地址（可以直接引用变量，console搞panel里面的获取就行）
14.deploylinux的centos（除了ubuntu外），gitee没有直链，不支持wget，修改为git clone。
15.deploylinux不能安装任何linux，研究后发现可能是tar导致的
16deploylinux不能启动linux，语法可能有问题
17.虚拟机镜像下载站删了，找文件搬运工放win7,win8和win10
18.wiki记住要写设备要求
19.RaspberryPI系统支持，并且默认模拟真实树莓派感觉（web图片，硬件模拟）
20.初始化向导和panel打开使用pm命令打开termux，优化体验
21.公告插入panel（走马灯
22.panel放时间，功能和log
23.进lite panel不用127，getip（socket调用或者django的8888，功能也一样）
24.username自定义，用户名放bin目录下面，快速显示，django的temple里面的右上角用户名ui显示读取bin下面的用户名
25.更新系统加apt update，apt upgrade，pip install git忽略的txt，最后pip update和git clone仓库
26.17功能改bash，避免报错
27.加个flyosvnc功能，使用novnc，在panel面板首页显示novnc和全屏预览
28.mcserver功能(用户要求可选）
29.asia2的服务和web放进panel功能
等暑假我也一起来，写个列表备忘。

**Comment by krishukr** [comment]
存在一个重大问题，抄袭
![image](https://user-images.githubusercontent.com/53934805/128618436-f306d8de-93a9-4a12-afeb-6e7aecdb11dc.png)

**Comment by AldarisX** [comment]
《但请尊重作者》

**Comment by AldarisX** [comment]
《人家作者说了没事》

**Comment by AldarisX** [comment]
《我还认识他》

**Comment by Kurokitu** [comment]
您涉及到的许可证可不止一个那么简单。
更何况在未经过允许的情况下使用了他人的开源项目并魔改版权声明信息。
在使用了GPL协议的情况下代码仍有加密部分。

年龄小不成熟无可厚非，在过程中确实能够看到有一定的基础，但有人指出您不对的地方是否能够考虑虚心接受并且修改。人都是这么个阶段过来的，急于求成想获得关注，可能反而会产生负面效应。
