### ISSUE TITLE
Xswl

### ISSUE THREAD

**Issue by GitHubNeko** [xingyujie/flyos#26]
Termux发行版？能详细解释吗？
![Screenshot_20210807_214230](https://user-images.githubusercontent.com/83487691/128602309-aee34310-ef5a-4d79-a617-558d0b4ee48b.jpg)

**Comment by TheInterestingSoul** [comment]
怕是tmoe改的？

**Comment by iy88** [comment]
xswl

**Comment by XuQingGen** [comment]
给爷整乐了

**Comment by GitHubNeko** [comment]
来自Termux开发人员之一的回复
![Screenshot_20210807_215853_org telegram messenger](https://user-images.githubusercontent.com/83487691/128602759-ec7ccd96-6908-4b43-83c4-5e31383aa4b8.jpg)

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128603604-c677cb33-91d2-4779-a5fe-0745516acba2.png)
乐了

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128603743-cafc5e62-3fcb-4ea2-ab9b-5aa8b8198707.png)

![image](https://user-images.githubusercontent.com/53934805/128603735-4e9edace-5d0c-49c6-9385-d9112a23d414.png)

又乐了

**Comment by krishukr** [comment]
> ![image](https://user-images.githubusercontent.com/53934805/128603743-cafc5e62-3fcb-4ea2-ab9b-5aa8b8198707.png)
> 
> ![image](https://user-images.githubusercontent.com/53934805/128603735-4e9edace-5d0c-49c6-9385-d9112a23d414.png)
> 
> 又乐了

![image](https://user-images.githubusercontent.com/53934805/128603816-6069c742-b2b8-4500-a185-3a438a8f21a6.png)


推特也是查不到的，乐死了

**Comment by Sherlockcxk** [comment]
只能算distribution

**Comment by Sherlockcxk** [comment]
readme上写的“original and complete”属实有点扯

**Comment by Sherlockcxk** [comment]
还有，别人肉，尊重一下作者吧，

**Comment by TheInterestingSoul** [comment]
> 还有，别人肉，尊重一下作者吧，

关于人肉你可能有点误解，皮子贱的人没办法好好说话
![a450d9b142ac37acb2f90df6d50156f3](https://user-images.githubusercontent.com/41455159/128604138-718ec09b-e8bd-4d0a-b79c-c922fda5b20f.jpg)

**Comment by Sherlockcxk** [comment]
@TheInterestingSoul 你知道侮辱罪吗

**Comment by Sherlockcxk** [comment]
建议你小心一点

**Comment by krishukr** [comment]
> 还有，别人肉，尊重一下作者吧，

我只是想说明这只是个自大的小学生罢了

**Comment by Sherlockcxk** [comment]
还有人 是有隐私权的

**Comment by krishukr** [comment]
> 还有人 是有隐私权的

他自己公开到主页上的

**Comment by Sherlockcxk** [comment]
> > 还有，别人肉，尊重一下作者吧，
> 
> 我只是想说明这只是个自大的小学生罢了

本人也一样，初中生

**Comment by Sherlockcxk** [comment]
但小学生就一定写不了代码吗？也未必吧

**Comment by TheInterestingSoul** [comment]
> 但小学生就一定写不了代码吗？也未必吧

不要偷换概念。小学生写OI最后进国家队为国争光，和小学生在B站上装逼吹嘘是两回事。

**Comment by krishukr** [comment]
> 但小学生就一定写不了代码吗？也未必吧

![image](https://user-images.githubusercontent.com/53934805/128604287-84db14a7-bd0e-4c0b-ab21-b188408147eb.png)

这就是他写的所谓无依赖XDD

**Comment by Sherlockcxk** [comment]
哈哈哈他用了bing

**Comment by Sherlockcxk** [comment]
还有readme上写的original and complete也很虚 确实
这个东西就是一个linux交互界面罢了

**Comment by krishukr** [comment]
> 哈哈哈他用了bing

？用的是w3m……

monyhar直呼内行

**Comment by Sherlockcxk** [comment]
艹我只看了第二行没看第三行代码

**Comment by TheInterestingSoul** [comment]
飞流直下三千尺
https://github.com/xingyujie/flyos/blob/3f9766de9dbaaa98fd02b27d4049e69c5217397a/kernel/boot/kernelconfig/kernelconf.sh#L1-L100

**Comment by krishukr** [comment]
> 飞流直下三千尺
> https://github.com/xingyujie/flyos/blob/3f9766de9dbaaa98fd02b27d4049e69c5217397a/kernel/boot/kernelconfig/kernelconf.sh#L1-L100

没关系，我统计的时候全都忽略空行和注释的

**Comment by Sherlockcxk** [comment]
都散了吧，这东西没什么好说的
技术上的虚假宣传我也见多了，笑笑就完事了

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128604674-1a0d056a-1a86-4ab7-955c-7b5485ddc6e6.png)

我谔谔

**Comment by krishukr** [comment]
> ![image](https://user-images.githubusercontent.com/53934805/128604674-1a0d056a-1a86-4ab7-955c-7b5485ddc6e6.png)
> 
> 我谔谔


https://github.com/yuri2peter/win10-ui/blob/master/js/win10.js

**Comment by MSCxar-0293** [comment]
> > ![image](https://user-images.githubusercontent.com/53934805/128603743-cafc5e62-3fcb-4ea2-ab9b-5aa8b8198707.png)
> > ![image](https://user-images.githubusercontent.com/53934805/128603735-4e9edace-5d0c-49c6-9385-d9112a23d414.png)
> > 又乐了
> 
> ![image](https://user-images.githubusercontent.com/53934805/128603816-6069c742-b2b8-4500-a185-3a438a8f21a6.png)
> 
> 推特也是查不到的，乐死了

还是个马迷
马迷震怒（（

**Comment by krishukr** [comment]
> > > ![image](https://user-images.githubusercontent.com/53934805/128603743-cafc5e62-3fcb-4ea2-ab9b-5aa8b8198707.png)
> > > ![image](https://user-images.githubusercontent.com/53934805/128603735-4e9edace-5d0c-49c6-9385-d9112a23d414.png)
> > > 又乐了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/53934805/128603816-6069c742-b2b8-4500-a185-3a438a8f21a6.png)
> > 推特也是查不到的，乐死了
> 
> 还是个马迷
> 马迷震怒（（

明显不是他啊

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128605025-f821f11b-f336-4a7b-9f14-0d57a6ceb44a.png)

继续乐乐

**Comment by MSCxar-0293** [comment]
> > > > ![image](https://user-images.githubusercontent.com/53934805/128603743-cafc5e62-3fcb-4ea2-ab9b-5aa8b8198707.png)
> > > > ![image](https://user-images.githubusercontent.com/53934805/128603735-4e9edace-5d0c-49c6-9385-d9112a23d414.png)
> > > > 又乐了
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/53934805/128603816-6069c742-b2b8-4500-a185-3a438a8f21a6.png)
> > > 推特也是查不到的，乐死了
> > 
> > 
> > 还是个马迷
> > 马迷震怒（（
> 
> 明显不是他啊

有道理
我搜他fb也是有大量同名账号
对自己名字的独特性真是有够自信（）
