### ISSUE TITLE
同志，你这个烂代码有点多啊

### ISSUE THREAD

**Issue by Sherlockcxk** [xingyujie/flyos#27]
![85534824-E8DE-4538-880A-310DB59D706A](https://user-images.githubusercontent.com/74444486/128603016-23bf05c4-dcb6-4263-a041-26204623b1ff.jpeg)
![DFDABF2C-F94D-448C-891B-2E2571FCDD99](https://user-images.githubusercontent.com/74444486/128603018-aa6b8652-b7a6-4949-aaa7-876191ae0e5c.jpeg)
你这个有一些凑代码的嫌疑

**Comment by Sherlockcxk** [comment]
“EXIT”.tolower()

**Comment by purofle** [comment]
> ![85534824-E8DE-4538-880A-310DB59D706A](https://user-images.githubusercontent.com/74444486/128603016-23bf05c4-dcb6-4263-a041-26204623b1ff.jpeg)
> ![DFDABF2C-F94D-448C-891B-2E2571FCDD99](https://user-images.githubusercontent.com/74444486/128603018-aa6b8652-b7a6-4949-aaa7-876191ae0e5c.jpeg)
> 你这个有一些凑代码的嫌疑

明明就是屎山，建议把标题改了（doge）

**Comment by Sherlockcxk** [comment]
屎山不至于

**Comment by Sherlockcxk** [comment]
但一般人是不会这样写代码的
@purofle

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128606311-e6def082-a6d5-451b-8e90-73d50b2a524c.png)
