### ISSUE TITLE
同志，说谎是不好的

### ISSUE THREAD

**Issue by krishukr** [xingyujie/flyos#30]
《五十万》
![image](https://user-images.githubusercontent.com/53934805/128605087-4a13f355-7f88-4194-9df8-fd6e61e2a537.png)

《没有抄》
![image](https://user-images.githubusercontent.com/53934805/128605104-e5c9d909-0d1f-4095-981f-34378f3004c0.png)

**Comment by krishukr** [comment]
《没有依赖》

![image](https://user-images.githubusercontent.com/53934805/128605412-923cf363-b1dd-4483-aec4-ea2c60d32941.png)

**Comment by 493505110** [comment]
草

**Comment by AlifeLine** [comment]
![image](https://user-images.githubusercontent.com/33149119/128607329-23ced9a4-823e-4706-9cba-836c2f90c089.png)
![image](https://user-images.githubusercontent.com/33149119/128607340-0f334a67-9e67-4c79-8381-058f74d72d8e.png)
聊天室的代码是抄的，注释都一样🤣

**Comment by AlifeLine** [comment]
![image](https://user-images.githubusercontent.com/33149119/128607481-3d8040be-fac1-4062-addd-949a9e4b6749.png)

打着开源的旗号，部分代码混淆加密还加入了卡密激活系统😂

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/128615737-b83a419f-7676-493c-acd7-e36d97d13829.png)
《大量财产》

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/128615840-6dc24fb9-d3f5-4159-9156-0efcc35294aa.png)
《源代码》(指BIN文件)

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/128615895-e5e057e0-59a6-4896-8564-6604d276910e.png)
（）

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/128616035-79897824-0f8b-41da-ac71-16cdf2fb9333.png)

**Comment by 493505110** [comment]
https://github.com/xingyujie/flyos/blob/master/kernel/boot/active/active.py
核心被加密,这算GPL-3?

**Comment by FYWinds** [comment]
![image](https://user-images.githubusercontent.com/74457127/128616778-cc567213-bd1b-4583-8efe-e331c1e1f75b.png)
别尬黑，看看这多高贵的“进度条”

**Comment by krishukr** [comment]
> ![image](https://user-images.githubusercontent.com/74457127/128616778-cc567213-bd1b-4583-8efe-e331c1e1f75b.png)
> 别尬黑，看看这多高贵的“进度条”

我昨天晚上在tg嘲讽过了XDD

**Comment by krishukr** [comment]
关了也没用，这都是实证
