### ISSUE TITLE
kernel都有部分代码加密了

### ISSUE THREAD

**Issue by Cpointerz** [xingyujie/flyos#31]
我就很好奇，用着GPL开源许可都有加密的代码。
某种意义上可以自己告自己

**Comment by AlifeLine** [comment]
那部分是用来检查授权的🤣
![image](https://user-images.githubusercontent.com/33149119/128609222-586d3b1f-c576-42d7-8d82-bea37236257b.png)

**Comment by Kurokitu** [comment]
草，这个授权不是写个文件就能过（
