### ISSUE TITLE
这个项目我王多鱼投了

### ISSUE THREAD

**Issue by yangyang233333** [xingyujie/flyos#33]

**Comment by Sherlockcxk** [comment]
我王思聪去年就投了

**Comment by krishukr** [comment]
我也投，一份卡密5块钱，卖爆

**Comment by krishukr** [comment]
> 我也投，一份卡密5块钱，卖爆

![image](https://user-images.githubusercontent.com/53934805/128617000-54323abc-f048-4482-b3a9-2f698ac1f3a7.png)

![image](https://user-images.githubusercontent.com/53934805/128617002-4ddb331d-a272-4c12-aace-f564c634ca5b.png)

就是这个太容易破解了，得改改XD
