### ISSUE TITLE
Q群迷惑发言大赏

### ISSUE THREAD

**Issue by krishukr** [xingyujie/flyos#34]
![image](https://user-images.githubusercontent.com/53934805/128618258-0b7c57a2-844f-43e5-afef-0077e5f00d77.png)
![image](https://user-images.githubusercontent.com/53934805/128618262-0ac4df2f-c672-43d5-8816-0cd3889b1d9e.png)
![image](https://user-images.githubusercontent.com/53934805/128618260-deb15338-7017-4661-bc41-63eaec7a2d21.png)
![image](https://user-images.githubusercontent.com/53934805/128618259-bb0ed282-00fb-4696-a298-40b23769de36.png)
![image](https://user-images.githubusercontent.com/53934805/128618263-926c8d5d-551c-410e-b508-02968fc8700a.png)
《道法白学了》

![image](https://user-images.githubusercontent.com/53934805/128618277-ab6c17a9-e83c-41f7-bb98-a7a6fbfd4c08.png)
![image](https://user-images.githubusercontent.com/53934805/128618303-ae12c94a-65cc-4298-875c-15327f4310e7.png)
《个人项目》

![image](https://user-images.githubusercontent.com/53934805/128618286-8777e534-3c36-4cd1-b6ad-ae4731332c63.png)
![image](https://user-images.githubusercontent.com/53934805/128618288-2aeffc3c-3a53-433e-8658-6bf6997ea6c4.png)
《他急了》

![image](https://user-images.githubusercontent.com/53934805/128618290-30129800-6de3-4cb3-914c-f54b8534063e.png)
《荣幸之至》

![image](https://user-images.githubusercontent.com/53934805/128618305-69664fbe-7e3e-482f-adcb-6328223827ee.png)
《确实》

**Comment by 493505110** [comment]
草

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618458-1c5d0a7e-4a5f-4c9f-bd27-f382ef084946.png)
《你消停罢》

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618495-54256e01-39e5-497b-a905-f2e742f5f7fe.png)
《开源》

![image](https://user-images.githubusercontent.com/53934805/128618498-5aac15d2-4151-4971-beae-9baea88de3c1.png)
《自打自脸》

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618590-a2eaa4da-0c60-40c5-957b-bef22a4060ee.png)
《骂人》

**Comment by 493505110** [comment]
建议叫他来tg看一看

**Comment by krishukr** [comment]
> 建议叫他来tg看一看

他能上tg吗XD

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618676-b5ccadfd-d7e1-4a0a-9c45-31c9c323df64.png)
![)W4~KBS1GY_}KJPH2 VNVIQ](https://user-images.githubusercontent.com/53934805/128618667-f6070221-5cd3-4189-804f-64b89f863643.jpg)
《哄堂大笑》

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618683-4c8d7405-dfeb-4063-bab0-5011f58bd150.png)
《自相矛盾》

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618687-671e6f48-b373-43a0-b2ec-42233e223318.png)
![image](https://user-images.githubusercontent.com/53934805/128618688-48098481-4120-4bd9-93a2-fa9e06829fb8.png)
《许可》

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618706-1a9ad6f0-2484-419c-a0c9-7c148c0923af.png)
《您真棒》

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618720-ab7530f6-2ad6-4639-9fa4-bdf6dbca88da.png)
《不打自招》

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618730-27b2f775-c767-4b8f-a503-ee7a73940f19.png)
《确实》

**Comment by 493505110** [comment]
> ![image](https://user-images.githubusercontent.com/53934805/128618706-1a9ad6f0-2484-419c-a0c9-7c148c0923af.png)
> 《您真棒》

![image](https://user-images.githubusercontent.com/29498336/128618750-237b100e-4753-4ed9-a37d-6b9405d30d10.png)

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618765-8a088d31-3308-4635-a22e-785094aecfb7.png)
《你行你上》

**Comment by krishukr** [comment]
> > ![image](https://user-images.githubusercontent.com/53934805/128618706-1a9ad6f0-2484-419c-a0c9-7c148c0923af.png)
> > 《您真棒》
> 
> ![image](https://user-images.githubusercontent.com/29498336/128618750-237b100e-4753-4ed9-a37d-6b9405d30d10.png)

千行

**Comment by TheNightmareX** [comment]
持续更新了属于是

**Comment by MSCxar-0293** [comment]
艹

**Comment by krishukr** [comment]
> 持续更新了属于是

直播呢属于是

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618792-b45ac728-61bc-4c73-abce-fae58c9dee14.png)
《不够的呢亲》

**Comment by TheNightmareX** [comment]
Close 警告⚠

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618836-1e2eede8-f715-4ff9-a176-1effa66d9a1e.png)
《认识》

**Comment by krishukr** [comment]
> Close 警告⚠

已经被close过一个了

**Comment by 493505110** [comment]
> Close 警告⚠

就算close了也能继续发下去

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618856-735d3cc0-aafe-4cc3-8d24-a597dcb88210.png)
《确实》

**Comment by TheNightmareX** [comment]
发是能发 但新来的人就看不到了哇 谁会没事儿点进closed里面看

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618859-011e3386-0043-4c22-8212-ca07d6eda243.png)
![image](https://user-images.githubusercontent.com/53934805/128618866-704ef808-5a99-43ac-aff5-897c11e65d24.png)
《没事》

**Comment by krishukr** [comment]
> 发是能发 但新来的人就看不到了哇 谁会没事儿点进closed里面看

他暂时在Q群对线，还没时间管GitHub

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618876-2fdb7bef-6dc2-41bd-a098-ef9662c1f540.png)
《经典》

![image](https://user-images.githubusercontent.com/53934805/128618887-09ef9dca-1621-480c-8dad-2a3bc2ae56b3.png)
《保留》

**Comment by TheNightmareX** [comment]
《关于我在GayHub看直播这件事》

**Comment by krishukr** [comment]
> 《关于我在GayHub看直播这件事》

XD

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/128618900-11ae3134-1443-4e8f-90e9-465bc76b2588.png)

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618903-73f7894f-b68e-4794-896d-18651fbaef53.png)
![image](https://user-images.githubusercontent.com/53934805/128618905-959ac670-2e77-40c7-a9d2-6c7cc9908ea5.png)
![image](https://user-images.githubusercontent.com/53934805/128618909-138f1733-bbdf-4636-a0ac-4c7f8c082b4c.png)

《无题》

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618917-ce26da7e-61e2-444b-a75a-8496d70fc52e.png)

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618921-9d10a1b2-66fc-47a9-8b16-79fca17dae5f.png)
《您》

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/128618935-e958962f-9661-4de8-8117-ad8872c9cb7d.png)

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618953-e64f74f2-35d2-4439-b1b9-fdbdc603728c.png)

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618960-b88c0bb4-2de3-4d3a-86fd-a85be230ac90.png)

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128618967-2a1c785c-7dc4-4c36-8c3a-8ce5cdb0d1f3.png)
《快乐》

**Comment by TheNightmareX** [comment]
> ![image](https://user-images.githubusercontent.com/53934805/128618967-2a1c785c-7dc4-4c36-8c3a-8ce5cdb0d1f3.png)
> 《快乐》

草“让我重拾自信”

**Comment by krishukr** [comment]
![image](https://user-images.githubusercontent.com/53934805/128619005-4a51acce-bf6a-4b88-b6bc-fcbefe9fa53f.png)

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/128619028-ae1e4eaa-c571-44ed-9130-6a44a53db0ba.png)

**Comment by TheNightmareX** [comment]
@krishukr  也是个OIer耶！😘

**Comment by krishukr** [comment]
> @krishukr 也是个OIer耶！😘

草，被发现了（（
我太菜了

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/128619077-42999019-3dc0-4b84-8712-66be8ecd08dd.png)

《我没错》

**Comment by TheNightmareX** [comment]
大型拷打现场了属于是

**Comment by krishukr** [comment]
我上课去了，请其他大佬接力直播（雾

**Comment by sakurayun** [comment]
《我没错》
![image](https://user-images.githubusercontent.com/30366696/128619134-ed65b4f5-d005-4465-b72e-b79f56c40672.jpeg)

**Comment by LiangYin233** [comment]
来打个卡

**Comment by LiangYin233** [comment]
“爱用不用”
“不用的滚出群”
《他急了》

**Comment by Kyomotoi** [comment]
https://web.archive.org/web/20210808025146/https://github.com/xingyujie/flyos/issues/34

已将此issue保存至档案馆，太好笑了我要保存

**Comment by krishukr** [comment]
> https://web.archive.org/web/20210808025146/https://github.com/xingyujie/flyos/issues/34
> 
> 已将此issue保存至档案馆，太好笑了我要保存

感谢（

**Comment by sakurayun** [comment]
《爱用不用不用滚》

**Comment by MSCxar-0293** [comment]
**支持FlyOS！**

**Comment by Creeper2333** [comment]
> **支持FlyOS！**

我记得你是[某个 flyos archive 仓库](https://github.com/FuckOS/flyos)的contributor之一吧（

**Comment by TheNightmareX** [comment]
@Creeper2333  嘘！别让他暴露了

**Comment by Creeper2333** [comment]
> @Creeper2333 嘘！别让他暴露了

大 声 密 谋

**Comment by Creeper2333** [comment]
> @Creeper2333 嘘！别让他暴露了

我现在有点慌
我感觉邢博士开学会来找我面♂基

**Comment by Creeper2333** [comment]
> @Creeper2333 嘘！别让他暴露了

我感觉邢博士他……
开学会来找我面♂基……

**Comment by TheNightmareX** [comment]
> > @Creeper2333 嘘！别让他暴露了
> 
> 我感觉邢博士他……
> 开学会来找我面♂基……

敢情你们还一个学校的🤔

**Comment by Creeper2333** [comment]
> > > @Creeper2333 嘘！别让他暴露了
> > 
> > 
> > 我感觉邢博士他……
> > 开学会来找我面♂基……
> 
> 敢情你们还一个学校的🤔

我的邮箱 hsiaowei_lu@foxmail.com
被邢博士盯着有点害怕

**Comment by Creeper2333** [comment]
> > > @Creeper2333 嘘！别让他暴露了
> > 
> > 
> > 我感觉邢博士他……
> > 开学会来找我面♂基……
> 
> 敢情你们还一个学校的🤔

算了，直接加我qq吧 1642253282
加好了记得提醒我把这条删掉
