### ISSUE TITLE
你凭什么不让我说

### ISSUE THREAD

**Issue by Cpointerz** [xingyujie/flyos#36]
你用GPL许可，放出被加密的代码，你还closed。
什么意思？
我要不要请律师帮忙告你？
![SB](https://user-images.githubusercontent.com/57285730/128618369-8c3fe855-fc6e-4d74-a64c-8fe5a40564e5.PNG)

**Comment by TheInterestingSoul** [comment]
写一个狂开issue的GitHub Action炸他库

**Comment by TheNightmareX** [comment]
> 写一个狂开issue的GitHub Action炸他库

!! Block 警告🤣

**Comment by TheInterestingSoul** [comment]
这个简单，就算被block掉，也可以用reference的形式在issue下留痕，
写个action无限提交commit，在commit message中写下这个issue的地址就行

**Comment by TheNightmareX** [comment]
哈哈 绝
