### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by nkxingxh** [xingyujie/flyos#49]
#30  #34

**Comment by nkxingxh** [comment]
#35 

请问为何有关许可证的issue被关闭了，这问题好像还没解决吧

**Comment by zhongwanlamian** [comment]
Почему закрывается вопрос с лицензией? Эта проблема кажется нерешенной

**Comment by zhongwanlamian** [comment]
#35 
Почему закрывается вопрос с лицензией? Эта проблема кажется нерешенной

**Comment by WEN0797** [comment]
![19f4697ca18d82f4](https://user-images.githubusercontent.com/47151663/128813144-706a5b64-a54d-4e4b-9fcb-481685c5d6de.jpg)
RT 🔝
