### ISSUE TITLE
十分期待flyos发展，提一些建议

### ISSUE THREAD

**Issue by AldarisX** [xingyujie/flyos#55]
### 这是我的一些希望

---

* Roadmap
尽快出个roadmap，让人们看到希望

* i18n
像这种大型项目都是多国语言的，不知道flyos什么时候才能国际化

* 官网
官网目前还在用的GitHub Pages，这不是这种大项目该用的！应该尽快转移到flyos云上，这种大型项目就应该使用自己的云服务器集群

**Comment by Misaka-L** [comment]
+10086

**Comment by Alphaly2K** [comment]
#### 虽然第一点鄙人学识浅薄看不懂啊但是还是觉得好厉害
## 总之
自己的服务器集群一定要有

建议对接像统计接口，看看flyos大量用户到底是有多么的大量

然后尽快摆脱Linux内核，自研内核并淦翻如今御三家

加油！

**Comment by MSCxar-0293** [comment]
支持！

# FlyOS值得更好的！

**Comment by xingyujie** [comment]
感谢反馈，我会努力修复的

**Comment by EdwardLab** [comment]
更新了你的issue已完成
