### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by ShenMian** [xingyujie/flyos#56]
第一次看到这个视频标题就知道会'火', 所以当天下午特地再看了一遍 Bilibili 的评论和 Github 的 Issues.
很多人在 Bilibili 上展示自己的作品, 也得到了不少的鼓励和支持. 相对于刚上初中的学生来说能花这么多时间写代码还不错.
但我觉得学习编程的路上应该要保持一颗不骄不躁的初心, 视频的标题明显过于夸张了.

1. Github 仓库代码实际统计确实和宣传的 50 万行差距较大, 而这些统计出来的才是真正的代码数量.
2. 代码数量不能说明什么, 质量才是重点. 应该尽量保持项目体积的增长, 复杂庞大的代码库将大大提高继续开发和维护的难度. 
3. 在计算机这方面有很多年纪很小却十分有才的人, 保持谦逊是应该的.

如果没有过于夸张的虚假宣传, 以及对开源项目版权的不尊重的话, 相信你会得到更多支持者的.
谁都犯过错, 就看有没有及时**改正**了.

> 以上仅个人见解, 如有不足还请指出.

**Comment by GreyElaina** [comment]
https://github.com/jsun969/flyos/issues/10
我希望该项目的维护者 @xingyujie 能够直面自己所做过的事情, 并对此做出反省.
让这风暴停下吧.

**Comment by ShenMian** [comment]
GC.
