### ISSUE TITLE
`恶俗维基`过来的😅

### ISSUE THREAD

**Issue by esudoji** [xingyujie/flyos#65]
你恶俗了吗
https://esu.dog/%E9%82%A2%E5%AE%87%E6%9D%B0
需要翻墙

**Comment by Creeper2333** [comment]
小心邢博士跟你面♂基
![](https://i0.hdslb.com/bfs/emote/e64af664d20716e090f10411496998095f62f844.png)

**Comment by 2k20** [comment]
我超，上下啊
