### ISSUE TITLE
flyos什么的还有在做吗

### ISSUE THREAD

**Issue by Creeper2333** [xingyujie/flyos#73]
邢同学中考了否

**Comment by xingyujie** [comment]
没有

**Comment by Creeper2333** [comment]
虽然之前是被乐子吸引来的
但是还是祝你冬至快乐

另：我在绵中2021级，1年后可能有机会找你本人？

**Comment by xingyujie** [comment]
祝你也冬至快乐，Christmas Eve快乐，不过你找我干嘛😥

**Comment by konata233** [comment]
邢同学后天中考？

**Comment by xingyujie** [comment]
对的，目前在开发3.0版本，关注我推特查看最新进度
https://twitter.com/EdwardHsingTech/status/1666847111797780486?t=oc71fUmjjmALIWFf9s8AWg&s=19

**Comment by konata233** [comment]
你是填的绵中一志愿吗

**Comment by konata233** [comment]
> 对的，目前在开发3.0版本，关注我推特查看最新进度 https://twitter.com/EdwardHsingTech/status/1666847111797780486?t=oc71fUmjjmALIWFf9s8AWg&s=19

关注了已经

**Comment by xingyujie** [comment]
额，，，你咋怎么关心我🥲

**Comment by konata233** [comment]
不是所有人都像我一样无聊的

**Comment by konata233** [comment]
> 额，，，你咋怎么关心我🥲

问问罢了

**Comment by xingyujie** [comment]
嗯不说，你在哪里

**Comment by konata233** [comment]
绵中

**Comment by xingyujie** [comment]
噢噢行吧

**Comment by konata233** [comment]
> 绵中

我的资料卡里面写了的

**Comment by xingyujie** [comment]
行吧🙂

**Comment by konata233** [comment]
那你明天中考了，祝你考试顺利

**Comment by xingyujie** [comment]
谢谢你
